name: Publish

on:
  push:
    tags:
      - '[0-9]*'

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Build binary
        run: go build -ldflags="-s -w" -o worker .

      - uses: cachix/install-nix-action@v27
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: cachix/cachix-action@v15
        with:
          name: devenv

      - run: nix profile install nixpkgs#devenv

      - name: Build and push image
        run: |
          VERSION="${{ github.ref_name }}"
          CONTAINERS_REGISTRIES_CONF=/dev/null devenv container copy \
            --registry docker://ghcr.io/junctionio/ \
            --copy-args="--dest-creds ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}" \
            system-worker
          CONTAINERS_REGISTRIES_CONF=/dev/null nix run nixpkgs#skopeo -- copy \
            --src-creds "${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}" \
            --dest-creds "${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}" \
            docker://ghcr.io/junctionio/system-worker:latest \
            docker://ghcr.io/junctionio/system-worker:${VERSION}
